class HeaderErrorCode:
    UNAUTHORIZED_ACCESS = 401
    INTERNAL_SERVER_ERROR = 500
    MISSING_MONTHLY_REPORTING_CURRENT_PERIOD = 412
    OBJECT_RESOURCE_NOT_FOUND = 400
    MONTHLY_REPORT_ALREADY_EXISTS_WITH_INPROGRESS = 409
    MONTHLY_REPORT_ALREADY_EXISTS_WITH_COMPLETED = 409
    DELETED_SUCCESSFULLY = 204

    INVALID_FILE_FORMAT = 422

    ALL_SIGHT_CONNECTION = 407
    RESOURCE_NOT_FOUND = 404