# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='accounting_type',
            field=models.CharField(choices=[('Quickbooks', 'Quickbooks'), ('Zero', 'Zero'), ('Sage', 'Sage')], default='Quickbooks', max_length=60),
        ),
    ]
