# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_accounting_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymeta',
            old_name='reporting_connection_type',
            new_name='monthly_reporting_sync_method',
        ),
        migrations.RemoveField(
            model_name='companymeta',
            name='last_reporting_period',
        ),
        migrations.RemoveField(
            model_name='companymeta',
            name='qbo_auth_token',
        ),
        migrations.AddField(
            model_name='companymeta',
            name='accounting_setup_last_page',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='accounting_setup_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='monthly_reporting_active_period',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='monthly_reporting_last_page',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='monthly_reporting_last_period_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='monthly_reporting_next_period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
