# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170831_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymeta',
            old_name='monthly_reporting_active_period',
            new_name='monthly_reporting_current_period',
        ),
    ]
