# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170831_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymeta',
            old_name='accounting_setup_last_page',
            new_name='last_page',
        ),
        migrations.RemoveField(
            model_name='companymeta',
            name='monthly_reporting_last_page',
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='monthly_reporting_last_step',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='monthly_reporting_sync_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='qb_connect_desktop_version',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
