# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170901_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='is_initial_setup',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='accounting_setup_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')], default='NOT_STARTED', max_length=20, null=True),
        ),
    ]
