# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20170907_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accounting_type',
            field=models.CharField(choices=[('Quickbooks', 'Quickbooks'), ('Xero', 'Xero'), ('Sage', 'Sage')], default='Quickbooks', max_length=60),
        ),
    ]
