# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170919_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companymeta',
            old_name='monthly_reporting_last_period_status',
            new_name='monthly_reporting_current_period_status',
        ),
    ]
