# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170920_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='qb_desktop_installed',
            field=models.BooleanField(default=False),
        ),
    ]
