# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_companymeta_qb_desktop_installed'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='signoff_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='signoff_by_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='signoff_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='last_page',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
