# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20171004_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymeta',
            name='signoff_by_name',
        ),
        migrations.RemoveField(
            model_name='companymeta',
            name='signoff_by_title',
        ),
        migrations.RemoveField(
            model_name='companymeta',
            name='signoff_date',
        ),
    ]
