# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20171004_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
