# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-15 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='trialbalance_dl_complete',
            field=models.BooleanField(default=False),
        ),
    ]
