# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_companymeta_trialbalance_dl_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymeta',
            name='chartofaccounts_last_refresh_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companymeta',
            name='trialbalance_last_refresh_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
