# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20171016_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='current_fiscal_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='parent_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
    ]
