# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-16 22:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20171025_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalYearEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fye_start_date', models.DateField()),
                ('fye_end_date', models.DateField()),
                ('label', models.CharField(max_length=60)),
                ('last_update_date', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
            options={
                'db_table': 'fiscalyearend',
            },
        ),
    ]
