# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 11:26
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL),
        ('accounts', '0020_fiscalyearend'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPasswordRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)', message='Invalid data')])),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('request_time', models.DateTimeField(blank=True, null=True)),
                ('expiry_time', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'forgot_password_request',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=None)),
                ('end_time', models.DateTimeField(default=None)),
                ('is_first_time', models.BooleanField(default=True)),
                ('auth_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_ACCESS_TOKEN_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='auth_key',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='Atleast 10 characters required')]),
        ),
        migrations.AddField(
            model_name='company',
            name='secret_key',
            field=models.CharField(default='', max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='Atleast 10 characters required')]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_session_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='company',
            name='external_id',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required'), django.core.validators.RegexValidator('^([(\\[]|[a-zA-Z0-9_\\s]|["-\\.\'#&!]|[)\\]])+$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(4, message='Atleast 4 characters required'), django.core.validators.RegexValidator('^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$', message='Invalid data')]),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='last_page',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='monthly_reporting_current_period_status',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='monthly_reporting_last_step',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='monthly_reporting_sync_method',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='companymeta',
            name='qb_connect_desktop_version',
            field=models.CharField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('(^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$)', message='Please enter a valid email id')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='external_id',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required'), django.core.validators.RegexValidator('^([(\\[]|[a-zA-Z0-9_\\s]|["-\\.\'#&!]|[)\\]])+$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required'), django.core.validators.RegexValidator('^([(\\[]|[a-zA-Z0-9_\\s]|["-\\.\'#&!]|[)\\]])+$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        # migrations.AlterUniqueTogether(
        #     name='contact',
        #     unique_together=set([('company', 'email')]),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='user',
        #     unique_together=set([('email',)]),
        # ),
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forgotpasswordrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
