# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 08:59
from __future__ import unicode_literals

from django.db import migrations
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180118_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_tag_error_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fiscalyearend',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
