# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180119_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpasswordrequest',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='fiscalyearend',
            table=None,
        ),
    ]
