# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0023_fiscal_year_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymeta',
            name='accounting_setup_status',
            field=models.CharField(blank=True, choices=[('NOT_STARTED', 'NOT_STARTED'),
                                                        ('ACCOUNTING_TYPE_CHOSEN', 'ACCOUNTING_TYPE_CHOSEN'),
                                                        ('IN_PROGRESS', 'IN_PROGRESS'), ('COMPLETE', 'COMPLETE')],
                                   default='NOT_STARTED', max_length=50, null=True),
        ),
    ]
