# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_accounting_setup_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_tag_error_notified',
            field=models.BooleanField(default=False, help_text='No Need to Change. Auto Updation Field'),
        ),
    ]
