# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 18:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20180202_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='Atleast 3 characters required'), django.core.validators.RegexValidator('^([(\\[]|[a-zA-Z0-9_\\s]|["-\\.\'#&!]|[)\\]])+$')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(1, message='Atleast 3 characters required'), django.core.validators.RegexValidator('^([(\\[]|[a-zA-Z0-9_\\s]|["-\\.\'#&!]|[)\\]])+$')]),
        ),
    ]
