# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 13:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180207_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAccountingConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xero_accounting_type', models.CharField(choices=[(' ', ' ------- '), ('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default=' ', max_length=50)),
                ('auth_key', models.CharField(default=' ', max_length=500, validators=[django.core.validators.MinLengthValidator(10, message='Atleast 10 characters required')])),
                ('secret_key', models.TextField(default=' ', help_text='Copy & paste the rsa key content from generated .pem for xero private type accounting access. Otherwise secret key required.', validators=[django.core.validators.MinLengthValidator(10, message='Atleast 10 characters required')])),
            ],
            options={
                'db_table': 'companyaccountingconfiguration',
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='auth_key',
        ),
        migrations.RemoveField(
            model_name='company',
            name='secret_key',
        ),
        migrations.AlterField(
            model_name='company',
            name='accounting_type',
            field=models.CharField(choices=[('quickbooks', 'Quickbooks'), ('xero', 'Xero'), ('sage', 'Sage')], default='quickbooks', max_length=60),
        ),
        migrations.AddField(
            model_name='companyaccountingconfiguration',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
    ]
