# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20180207_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyaccountingconfiguration',
            name='auth_key',
            field=models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10, message='Atleast 10 characters required')]),
        ),
        migrations.AlterField(
            model_name='companyaccountingconfiguration',
            name='secret_key',
            field=models.TextField(blank=True, help_text='Copy & paste the rsa key content from generated .pem for xero private type accounting access. Otherwise secret key required.', null=True, validators=[django.core.validators.MinLengthValidator(10, message='Atleast 10 characters required')]),
        ),
        migrations.AlterField(
            model_name='companyaccountingconfiguration',
            name='xero_accounting_type',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=50, null=True),
        ),
    ]
