# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20180213_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingconfiguration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accountingconfiguration',
            name='xero_accounting_type',
            field=models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('PARTNER', 'Partner')], default='PUBLIC', max_length=50, null=True),
        ),
    ]
