# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20180207_1038'),
        ('accounts', '0031_auto_20180214_0530'),
    ]

    operations = [
    ]
