# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_merge_20180216_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountingconfiguration',
            old_name='auth_key',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='accountingconfiguration',
            old_name='secret_key',
            new_name='client_secret',
        ),
        migrations.RenameField(
            model_name='accountingconfiguration',
            old_name='xero_accounting_type',
            new_name='type',
        ),
    ]
