# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20180216_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMaintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='user',
        #     name='is_session_active',
        # ),
        migrations.AddField(
            model_name='user',
            name='enforce_tfa_enabled',
            field=models.BooleanField(default=False, verbose_name='Enforce Two-factor Auth'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_logged_in',
            field=models.BooleanField(default=False, verbose_name='User Logged In'),
        ),
        # migrations.AddField(
        #     model_name='user',
        #     name='is_password_reset',
        #     field=models.BooleanField(default=True, verbose_name='Force Password Change'),
        # ),
        migrations.AddField(
            model_name='user',
            name='is_tfa_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Two-factor Auth'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_tfa_setup_completed',
            field=models.BooleanField(default=False, help_text='No Need to Change. Auto Updation Field', verbose_name='Two-factor Auth setup completed'),
        ),
        migrations.AddField(
            model_name='user',
            name='tfa_secret_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Two Factor Auth Secret Code'),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_guide_enabled',
            field=models.BooleanField(default=True, verbose_name='User Tour Guide'),
        ),
        migrations.AlterField(
            model_name='accountingconfiguration',
            name='accounting_type',
            field=models.CharField(choices=[('Quickbooks', 'Quickbooks'), ('Xero', 'Xero'), ('Sage', 'Sage')], default='Quickbooks', max_length=60),
        ),
        migrations.AlterField(
            model_name='company',
            name='accounting_type',
            field=models.CharField(choices=[('Quickbooks', 'Quickbooks'), ('Xero', 'Xero'), ('Sage', 'Sage')], default='Quickbooks', max_length=60),
        ),
        migrations.AddField(
            model_name='loggedinuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
