# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180417_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_session_active',
        ),
        migrations.AddField(
            model_name='user',
            name='is_password_reset',
            field=models.BooleanField(default=True, verbose_name='Force Password Change'),
        ),
    ]
