# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20180418_1707'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='espressocontact',
            index=models.Index(fields=['company'], name='espressocon_company_058a34_idx'),
        ),
        migrations.AddIndex(
            model_name='espressocontact',
            index=models.Index(fields=['contact', 'company'], name='espressocon_contact_2f828e_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['company'], name='contact_company_ae8bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='companymeta',
            index=models.Index(fields=['company'], name='companymeta_company_4da6f4_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyearend',
            index=models.Index(fields=['company', 'is_active'], name='accounts_fi_company_db49ac_idx'),
        ),
        migrations.AddIndex(
            model_name='loggedinuser',
            index=models.Index(fields=['user'], name='accounts_lo_user_id_2bdfbd_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_usernam_b79065_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_email_7bbb4c_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user'], name='accounts_us_user_id_691a59_idx'),
        ),
        migrations.AddIndex(
            model_name='forgotpasswordrequest',
            index=models.Index(fields=['user'], name='forgot_pass_user_id_5a956a_idx'),
        ),
        migrations.AddIndex(
            model_name='forgotpasswordrequest',
            index=models.Index(fields=['token'], name='forgot_pass_token_2ec115_idx'),
        ),
    ]
