# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20170822_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='gl_account_currency',
            field=models.CharField(max_length=3, verbose_name='Account Currency'),
        ),
    ]
