# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20170822_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='gl_account_id',
            field=models.IntegerField(null=True),
        ),
    ]
