# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20170823_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coa',
            name='gl_account_desc',
        ),
        migrations.RemoveField(
            model_name='coa',
            name='gl_detail_account_type',
        ),
    ]
