# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20170823_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatemententrytag',
            name='abstract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialstatemententrytag',
            name='formula',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='financialstatemententrytag',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='financialstatemententrytag',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
    ]
