# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20170823_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatemententrytag',
            name='tag_id',
            field=models.IntegerField(null=True),
        ),
    ]
