# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_auto_20170823_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='trialbalance',
            name='period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
