# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20170823_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalance',
            name='period',
            field=models.DateField(default=None),
        ),
    ]
