# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20170823_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='coamap',
            name='is_mapped',
            field=models.BooleanField(default=False),
        ),
    ]
