# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_quickbooklogin'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountingoauth2',
            table='accountingoauth2',
        ),
    ]
