# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_auto_20170907_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatemententrytag',
            name='generated_id',
            field=models.CharField(blank=True, max_length=65, null=True),
        ),
    ]
