# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_auto_20170919_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='coamap',
            name='verified_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
