# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_coamap_verified_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatemententrytag',
            name='all_sight_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatemententrytag',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
