# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_auto_20171102_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coamap',
            options={'verbose_name': 'Chart of Accounts Map'},
        ),
    ]
