# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 11:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_auto_20171102_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuickBookLogin',
            new_name='LoginInfo',
        ),
        migrations.AddField(
            model_name='accountingoauth2',
            name='accessSecretKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountingoauth2',
            name='tokenAcitvatedOn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accountingoauth2',
            name='tokenExpiryON',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountingoauth2',
            name='realmId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accountingoauth2',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coa',
            name='gl_account_currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')], verbose_name='Account Currency'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='gl_account_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coa',
            name='gl_account_name',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')], verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='gl_account_type',
            field=models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')], verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='coamap',
            name='cust_account_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coamap',
            name='cust_account_name',
            field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='coamap',
            name='espresso_account_name',
            field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='gl_account_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
