# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_auto_20180118_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingoauth2',
            name='accessSecretKey',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountingoauth2',
            name='refreshToken',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
