# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_auto_20180118_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='gl_account_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
