# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_auto_20180206_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialbalance',
            name='gl_account_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
