# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_auto_20180207_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingoauth2',
            name='refreshToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
