# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 17:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_auto_20180209_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='gl_account_bal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Account Balance'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='gl_account_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast 3 characters required')], verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='gl_account_type',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast 3 characters required')], verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='coamap',
            name='cust_account_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='coamap',
            name='cust_account_name',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='coamap',
            name='espresso_account_name',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast 3 characters required')]),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='trialbalance',
            name='debit',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
