# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 12:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_auto_20180207_1307'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='coa',
            name='gl_account_currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='Atleast a character required')], verbose_name='Account Currency'),
        ),

        migrations.AlterField(
            model_name='coa',
            name='gl_account_name',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast a character required')], verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='coa',
            name='gl_account_type',
            field=models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast a character required')], verbose_name='Account Type'),
        ),
        
        migrations.AlterField(
            model_name='coamap',
            name='cust_account_name',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast a character required')]),
        ),
        migrations.AlterField(
            model_name='coamap',
            name='espresso_account_name',
            field=models.CharField(blank=True, max_length=128, validators=[django.core.validators.MinLengthValidator(1, message='Atleast a character required')]),
        ),
   

        migrations.AlterField(
            model_name='trialbalance',
            name='gl_account_id',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
