# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_auto_20180209_0906'),
        ('accounting', '0033_auto_20180215_1229'),
    ]

    operations = [
    ]
