# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 13:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_merge_20180216_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='gl_account_currency',
            field=models.CharField(max_length=3, validators=[django.core.validators.MinLengthValidator(3, message='Atleast 3 characters required')], verbose_name='Account Currency'),
        ),
        migrations.AlterField(
            model_name='defaultaccounttagmapping',
            name='software',
            field=models.CharField(choices=[('Quickbooks', 'Quickbooks'), ('Xero', 'Xero'), ('Sage', 'Sage')], max_length=60),
        ),
    ]
