# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_auto_20180417_1329'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='defaultaccounttagmapping',
            index=models.Index(fields=['software'], name='defaultacco_softwar_b5e047_idx'),
        ),
        migrations.AddIndex(
            model_name='coamap',
            index=models.Index(fields=['company', 'cust_account_id'], name='coamap_company_c70be8_idx'),
        ),
        migrations.AddIndex(
            model_name='trialbalance',
            index=models.Index(fields=['company', 'period', 'gl_account_id'], name='trialbalanc_company_b42df3_idx'),
        ),
        migrations.AddIndex(
            model_name='coa',
            index=models.Index(fields=['company', 'gl_account_id', 'gl_account_name', 'gl_account_type'], name='coa_company_3cd6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='coa',
            index=models.Index(fields=['company', 'gl_account_name', 'gl_account_type'], name='coa_company_2c46d5_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingoauth2',
            index=models.Index(fields=['company'], name='accountingo_company_187e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='logininfo',
            index=models.Index(fields=['company'], name='accounting__company_d502ed_idx'),
        ),
    ]
