# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 19:52
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatementEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30, null=True)),
                ('item_category', models.CharField(max_length=30, null=True)),
                ('period_ending', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=3)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
            options={
                'db_table': 'financialstatemententry',
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Due', 'Due'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('Over Due', 'Over Due')], max_length=32)),
                ('period_ending', models.DateField()),
                ('due_date', models.DateField()),
                ('submitted_on', models.DateField(blank=True, null=True)),
                ('lookup_period', models.CharField(blank=True, max_length=8, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
            ],
            options={
                'db_table': 'monthlyreport',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_question_if', models.CharField(blank=True, max_length=20)),
                ('question_text', models.TextField()),
                ('question_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), blank=True, default=list, null=True, size=None)),
                ('short_tag', models.CharField(max_length=20)),
                ('answer_data_type', models.CharField(max_length=10)),
                ('answer_validation_regex', models.CharField(blank=True, max_length=254)),
                ('ask_order', models.IntegerField()),
                ('show_on_ui', models.BooleanField(default=False)),
                ('common_to_all_companies', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Question')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('purpose', models.TextField()),
            ],
            options={
                'db_table': 'questioncategory',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.QuestionCategory'),
        ),
        migrations.AddField(
            model_name='financialstatemententry',
            name='monthly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.MonthlyReport'),
        ),
        migrations.AddField(
            model_name='answer',
            name='monthly_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.MonthlyReport'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.Question'),
        ),
    ]
