# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatemententry',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='financialstatemententry',
            name='item_name',
        ),
        migrations.AddField(
            model_name='financialstatemententry',
            name='statement_type',
            field=models.CharField(choices=[('Income Statement', 'Income Statement'), ('Balance Sheet', 'Balance Sheet'), ('Cash Flow', 'Cash Flow')], default='Income Statement', max_length=60),
        ),
    ]
