# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20170824_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatemententry',
            name='entry_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
