# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_auto_20170823_2128'),
        ('reporting', '0003_financialstatemententry_entry_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatemententry',
            name='fse_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.FinancialStatementEntryTag'),
        ),
    ]
