# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20170901_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='signoff_by_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='signoff_by_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='signoff_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
