# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_auto_20171018_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
