# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0009_auto_20171021_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatemententry',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialstatemententry',
            name='period_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
