# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_auto_20171025_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='next_question_if',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
