# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 13:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180417_1329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0012_auto_20180118_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousReportEditLogger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(choices=[('Income Statement', 'Income Statement'), ('Balance Sheet', 'Balance Sheet'), ('Answer', 'Answer')], max_length=60, verbose_name='Section Name')),
                ('old_value', models.CharField(max_length=512, null=True, verbose_name='Old Value')),
                ('new_value', models.CharField(max_length=512, null=True, verbose_name='New Value')),
                ('date_changed', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Company')),
                ('finacial_statement_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.FinancialStatementEntry', verbose_name='Changed Finacial Tag')),
                ('question_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.Question', verbose_name='Changed Question')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporting.MonthlyReport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
