# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-31 09:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_previousreporteditlogger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatemententry',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='signoff_by_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^([(\\[]|[a-zA-Z0-9_\\s]|[[\\\\/"-\\.\'#&!]|[)\\]])+$')]),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='signoff_by_title',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^([(\\[]|[a-zA-Z0-9_\\s]|[[\\\\/"-\\.\'#&!]|[)\\]])+$')]),
        ),
        migrations.AlterField(
            model_name='previousreporteditlogger',
            name='finacial_statement_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reporting.FinancialStatementEntry', verbose_name='Changed Financial Tag'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['common_to_all_companies', 'show_on_ui', 'company'], name='question_common__4d9fab_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['company', 'monthly_report', 'question'], name='answer_company_f25d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatemententry',
            index=models.Index(fields=['company', 'statement_type', 'fse_tag'], name='financialst_company_a9a1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='financialstatemententry',
            index=models.Index(fields=['company', 'period_ending', 'statement_type', 'fse_tag'], name='financialst_company_77ba31_idx'),
        ),
        migrations.AddIndex(
            model_name='questioncategory',
            index=models.Index(fields=['group_name'], name='questioncat_group_n_b9efa4_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['company', 'period_ending'], name='monthlyrepo_company_b9dd5e_idx'),
        ),
    ]
